theme: jekyll-theme-dinky
title: SMT-COMP
description: The International Satisfiability Modulo Theories (SMT) Competition.
collections:
    divisions_2019:
        output: true
        permalink: /2019/divisions/:name
    participants_2019:
        output: true
        permalink: /2019/participants/:name
    results_2019:
        output: true
        permalink: /2019/results/:name
    results_summary_2019:
        output: true
        permalink: /2019/results/:name
    results_competition_wide_2019:
        output: true
        permalink: /2019/results/:name
    news_2019:
        output: true
        permalink: /2019/news/:name

    news_2018:
        output: true
        permalink: /2018/news/:name

    news_2017:
        output: true
        permalink: /2017/news/:name
