theme: jekyll-theme-dinky
title: SMT-COMP
description: The International Satisfiability Modulo Theories (SMT) Competition.
base_url: https://homepages.dcc.ufmg.br/~hbarbosa/tmp/smtcomp-2020-alternate/
collections:
    divisions_2021:
        output: true
        permalink: /2021/divisions/:name
    participants_2021:
        output: true
        permalink: /2021/participants/:name
    results_2021:
        output: true
        permalink: /2021/results/:name

    news_2020:
        output: true
        permalink: /2020/news/:name
    divisions_2020:
        output: true
        permalink: /2020/divisions/:name
    participants_2020:
        output: true
        permalink: /2020/participants/:name
    results_2020:
        output: true
        permalink: /2020/results/:name
    disagreements_2020:
        output: true
        permalink: /2020/disagreements/:name

    divisions_2019:
        output: true
        permalink: /2019/divisions/:name
    participants_2019:
        output: true
        permalink: /2019/participants/:name
    results_2019:
        output: true
        permalink: /2019/results/:name
    news_2019:
        output: true
        permalink: /2019/news/:name

    news_2018:
        output: true
        permalink: /2018/news/:name

    news_2017:
        output: true
        permalink: /2017/news/:name

    bibtex:
